version: '2'
services:
  nginx:
    image: nginx:latest
    build:
      context: ./.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./bagi091:/var/www/bagi091
      - ./pwa:/var/www/pwa
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
    environment:
      FPM_HOST: "magento.test.pwa"
      FPM_PORT: "80"
      MAGENTO_ROOT: "/var/www/html"
      MAGENTO_RUN_MODE: "developer"
      UPLOAD_MAX_FILESIZE: "16M"
    links:
      - db
    depends_on:
      - db
    networks:
      - Magento-network

#  apache:
#    image: rafaelcgstz/magento2
#    build:
#      context: ./.docker
#    ports:
#      - "80:80" # web
#      - "9001:9000" # xdebug
#      # - "35729:35729" # live reload
#    volumes:
#      - ./src:/var/www/html
#      - ./bagi091:/var/www/bagi091
#      - ./pwa:/var/www/pwa
#      - ~/.composer:/var/www/.composer
#      - ~/.npm:/var/www/.npm
#      # - ~/.nvm:/var/www/.nvm
#    environment:
#      XDEBUG_CONFIG: "remote_host=localhost"
#      PHP_IDE_CONFIG: "serverName=Docker"
#    depends_on:
#      - db
#    links:
#      - db
#    networks:
#      - Magento-network

  db:
    image: mariadb
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - Magento-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - Magento-network

  redis-session:
    image: redis
    ports:
     - 6379
    networks:
      - Magento-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - Magento-network

networks:
  Magento-network:
    driver: bridge
