version: '3'
services:
  nginx:
    build:
      context: ./.docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/etc_mount:/etc/nginx
      - ./src:/var/www/html
      - ./bagi091:/var/www/bagi091
      - ./pwa:/var/www/pwa
    restart: always
    links:
      - db
      - php
    depends_on:
      - db
      - php

  php:
    build:
      context: ./.docker/php
    volumes:
      - ./src:/var/www/html
      - ./bagi091:/var/www/bagi091
      - ./pwa:/var/www/pwa

  db:
    image: mariadb
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  redis:
    image: redis
    ports:
     - 6379

  redis-session:
    image: redis
    ports:
     - 6379

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
